---
title: "Assignment 11new"
author: "Nicole Kneip"
date: "12/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##options(timeout=100000)

##download.file("https://sdsu.box.com/shared/static/neaac6yoqx9e9x4j8391lzozzy1949p7.zip", destfile = "salary.zip")

##system("unzip salary.zip")
```
```{r}
library(readr)
State_Employee_Payroll_Data_Calendar_Year_2015_through_Present <- read_delim("State_Employee_Payroll_Data_Calendar_Year_2015_through_Present.tsv", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
```

```{r}
df <- State_Employee_Payroll_Data_Calendar_Year_2015_through_Present
##df1 <- unique(df$`EmplId-Empl Rcd`)
dfsamp <- head(df,8500)

```


```{r}
library(dplyr)
df_full <- filter(dfsamp, dfsamp$`Full/Part` == "F")
df_fulltime <- filter(df, df$`Full/Part` == "F")
```


```{r}
library(plotrix)
dfsex <- df[df$Sex == 'M' | df$Sex == 'F',]
counts <- sort(table(dfsex$Sex), decreasing = TRUE)
p <- paste(round(counts/sum(counts), 2)*100, "%", sep = "")
lbls <- paste(names(counts), "\n", counts, p, sep = "  ") 
pie3D(counts, labels = lbls, explode = 0.05,
    main = "Pie chart of sex", labelcex = 1.0, labelpos=c(1.8, 5.0))
```

Figure 1.)  This figure shows the percentage of Males and Females within the data.  We can see that it pretty equal with the Females having a slightly higher percentage.  


```{r}
library(ggplot2)
df_full_M <- dfsex[dfsex$Sex == 'M',]
df_full_F <- dfsex[dfsex$Sex == 'F',]
ggplot(df_full_F) + geom_histogram(aes(df_full_F$`Salaries & Wages`),binwidth = 8) + xlim(0,200)
```

```{r}
ggplot(df_full_M) + geom_histogram(aes(df_full_M$`Salaries & Wages`),binwidth = 8) + xlim(0,200)
```
```

